
// AUTH

export const SET_SENT_CODE = "AUTH/SET_SENT_CODE"
export const INCREMENT_AUTH_STAGE = "AUTH/INCREMENT_AUTH_STAGE"
export const AUTH_USER = "AUTH/AUTH_USER"
export const LOGOUT = "AUTH/LOGOUT"
export const SET_AUTH_LOADING_TRUE = "AUTH/SET_AUTH_LOADING_TRUE"
export const SET_AUTH_LOADING_FALSE = "AUTH/SET_AUTH_LOADING_FALSE"
export const SET_AUTH_ERROR = "AUTH/SET_AUTH_ERROR"

// USERS

export const SET_USERS = "AUTH/SET_USERS"
export const ADD_USER = "AUTH/ADD_USER"
export const DELETE_USER = "AUTH/DELETE_USER"
export const SET_USER_LOADING_TRUE = "AUTH/SET_USER_LOADING_TRUE"
export const SET_USER_LOADING_FALSE = "AUTH/SET_USER_LOADING_FALSE"
export const SET_USER_ERROR = "AUTH/SET_USER_ERROR"
